name: destiny
description: File transfer app based on flutter and wormhole-william

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 16.0.0

environment:
  sdk: ">=2.12.0 <3.4.0"

dependencies:
  dart_wormhole_william:
    path: ./dart_wormhole_william
  flutter_screenutil: 5.2.0
  shared_preferences: ^2.0.6
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 17d4710c17f4913137e7ec931f6e71eaef443363
  file_picker: ^4.5.0
  intro_slider:
    git:
      url: https://github.com/shareef-dweikat/flutter-intro-slider
      ref: a9bb492412c68419900750fe12e0487e3a1168fb
  expand_widget:
    git:
      url: https://github.com/shareef-dweikat/expand_widget
      ref: 52dc9fa9cc62191de4724b46edae29143c18a059
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  path_provider: ^2.0.0
  dotted_border: ^2.0.0+1
  desktop_drop: ^0.3.0
  permission_handler: ^10.0.0
  flutter_spinkit: ^5.1.0
  provider: ^6.0.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  crypto: ^3.0.1
  msix: ^3.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    - family: MontserratExtraBold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
    - family: MontserratThin
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
    - family: MontserratLightItalic
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
    - family: Courier
      fonts:
        - asset: assets/fonts/Courier/CourierPrime-Regular.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/No-Sign-Up.png
    - assets/images/logo.png
    - assets/images/Laptop-to-mobile-transfer.png
    - assets/images/icons/CHECK.png
    - assets/images/icons/send.png
    - assets/images/icons/receive.png
    - assets/images/Device2Device.png
    - assets/images/intro-logo.png
    - assets/images/file-sent-white.png
    - assets/images/icons/SETTINGS-WHITE.png
    - assets/images/icons/SETTINGS-WHITE-with-circle.png
    - assets/images/icons/INFO-WHITE-with-circle.png
    - assets/images/icons/INFO-WHITE.png
    - assets/images/icons/Paste-white.png
    - assets/images/icons/Phone-Icon.png
    - assets/images/icons/Plus-Button-Large.png
    - assets/images/icons/WHITE-ARROW.png
    - assets/images/icons/Hamburger-Menu-White.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: Destiny
  publisher_display_name: "Least Authority TFA GmbH"
  publisher: "E=developers@leastauthority.com, CN=Least Authority TFA GmbH, O=Least Authority TFA GmbH, STREET=Thaerstr. 28 a, L=Berlin, S=Berlin, C=DE, OID.1.3.6.1.4.1.311.60.2.1.1=Berlin (Charlottenburg), OID.1.3.6.1.4.1.311.60.2.1.2=Berlin, OID.1.3.6.1.4.1.311.60.2.1.3=DE, SERIALNUMBER=HRB 183278, OID.2.5.4.15=Private Organization"
  identity_name: com.leastauthority.Destiny
  logo_path: .\assets\images\logo.png
  capabilities: internetClientServer
  build_windows: false
  sign_msix: false
